### ISSUE TITLE
gitignore doesn't have \n at EOF

### ISSUE THREAD

**Issue by ghost** [tenforwardconsulting/sagacious_succotash#14]
https://github.com/tenforwardconsulting/sagacious_succotash/blob/c1f302f80d9c5b096101fcf8da23419d7e225c56/lib/sagacious_succotash/app_builder.rb#L405

doesn't put a \n at the end

Also put spec/examples.txt in this file

**Comment by petitJAM** [comment]
While you're in there for this one, add `/db/backups` to the ignore as well.

**Comment by petitJAM** [comment]
`window.ProjectName = {};` in `application.js` needs it also, too, as well.

**Comment by petitJAM** [comment]
I bet you could spin up a dummy project and use some command line magic to find all files without EOF \n's
